apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-mongo-express-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-mongo-express
  template:
    metadata:
      labels:
        app: tickets-mongo-express
    spec:
      containers:
      - name: tickets-mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: tickets-mongo-secret
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: tickets-mongo-secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: tickets-mongo-configmap
              key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-mongo-express-service
spec:
  type: NodePort
  selector:
    app: tickets-mongo-express
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30001